### ISSUE TITLE
AttributeError on Book Chapter page

### ISSUE THREAD

**Issue by mauromsl** [openlibhums/books#72]
[AttributeError: 'NoneType' object has no attribute 'year'](https://open-library-of-humanities.sentry.io/issues/6049450668/?referrer=slack)

**Comment by ajrbyers** [comment]
This was fixed by 1984b7ca61141336807598596422b5ed83eae002

I've created a new relesase [v1.3.3 ](https://github.com/openlibhums/books/releases/tag/v1.3.3)and deployed it to Huddersfield where the error ocured.
